# Precision and Performance Settings
mixed_precision = "bf16"
save_precision = "bf16"
gradient_checkpointing = true
sdpa = true
highvram = true
persistent_data_loader_workers = true
num_cpu_threads_per_process = 1
max_data_loader_n_workers = 2
cache_text_encoder_outputs_to_disk = true
cache_latents_to_disk = true
fused_backward_pass = true
full_bf16 = true

# Model Paths
pretrained_model_name_or_path = "./models/flux/flux1-dev.safetensors"
clip_l = "./models/flux/clip_l.safetensors"
t5xxl = "./models/flux/t5xxl_fp16.safetensors"
ae = "./models/flux/ae.safetensors"
save_model_as = "safetensors"

# Output and logging Configuration
output_dir = "flux1-3e6"
output_name = "finesse_prodstudio"
save_every_n_steps = 100
log_with = "wandb"
logging_dir = "wandb"
log_tracker_name = "kohya-bg"
sample_every_n_steps = 100
sample_prompts = "sample_prompts.txt"

# Dataset
dataset_config = "data_config.toml"

# Training Settings
learning_rate = 3e-6
max_train_epochs = 40
seed = 42
max_grad_norm = 0.0

# Optimizer and Scheduler
optimizer_type = "adafactor"
optimizer_args = [
  "relative_step=False",
  "scale_parameter=False",
  "warmup_init=False"
]
lr_scheduler = "constant_with_warmup"

# Sampling and Inference
timestep_sampling = "shift"
discrete_flow_shift = 3.1582
model_prediction_type = "raw"
guidance_scale = 1.0
blocks_to_swap = 10



